### ISSUE TITLE
validating a reference + possible suggestion

### ISSUE THREAD

**Issue by sparker6** [jacobkap/ucrbook#10]
Hi Jacob - I'm seeing a reference in the literature to your book that "More recent comparisons of UCR-SHR to NVDRS, however, suggest that UCR-SHR underestimates homicides compared to NVDRS (Kaplan, [2021b](https://link.springer.com/article/10.1007/s10896-022-00487-2#ref-CR44))." 

I've searched through it a few times to find this citation and I am not seeing it. Am I mistaken? Would like to cite the book. 

Loftin et al. 2008 make this point for SHR vs. Vital stats. Maybe it is beyond the scope of the book, but a "why use nvdrs" citation might be a nice addition during the NIBRS transition, I'm not seeing one readily available.

**Comment by sparker6** [comment]
article: https://link.springer.com/article/10.1007/s10896-022-00487-2

**Comment by jacobkap** [comment]
Hi, I believe it is referencing Figure 6.1 here https://ucrbook.com/shr.html#agencies-reporting-3.

**Comment by sparker6** [comment]
Ty for the pointer! They are using the reference to compare NVDRS to SHR, which I do not see included in the figure (would be a hard comparison as NVDRS doesn't quite span the US yet). I suppose NVDRS gets most of the Vital Stats, but don't actually know if that's true. Thanks again!

**Comment by jacobkap** [comment]
Oh, I thought NVDRS was another name for the CDC WONDER data. You're right, I don't use NVDRS at all in this book.

**Comment by sparker6** [comment]
It looks like NVDRS gets more IPV-related homicide than the SHR even though it spans fewer states. NVDRS reached nationwide coverage in 2021 or so -- it could be a source of homicide data nationally but the 2020 data came out in Feb 2023 so maybe not
