### ISSUE TITLE
Broken link to your UCR data

### ISSUE THREAD

**Issue by dylanbrewer** [jacobkap/ucrbook#9]
The following line includes a broken link:

"Finally, I have my own collection of UCR data [available publicly on openICPSR](https://www.openicpsr.org/openicpsr/search/studies?start=0&ARCHIVE=openicpsr&sort=score%20desc%2CDATEUPDATED%20desc&rows=25&q=jacob%20kaplan%27s%20concatenated%20files), a site which allows people to submit their data for public access."

In addition, I cannot locate the data files on openicpsr, so maybe they were taken down?

**Comment by jacobkap** [comment]
The link works now.
